config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events
  resources :users, only: [:show, :edit, :update]

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]
    post :show, on: :member
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :event, presence: true
  validates :user, presence: true
  validates :photo, presence: true

  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where "id IS NOT NULL"}
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_photo, only: [:destroy]

  def create
    @new_photo = @event.photos.build(photo_params)
    @new_photo.user = current_user

    if @new_photo.save
      notify_subscribers(@event, @new_photo)
      redirect_to @event, notice: I18n.t('controllers.photos.created')
    else
      render 'events/show', alert: I18n.t('controllers.photos.error')
    end
  end

  def destroy
    message = {notice: I18n.t('controllers.photos.destroyed')}

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = {alert: I18n.t('controllers.photos.error')}
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end

  def notify_subscribers(event, photo)
    all_emails = (event.subscriptions.map(&:user_email) + [event.user.email]).uniq - [photo.user.email]
    all_emails.each do |email|
      MailDeliveryJob.perform(event, photo, email)
    end
  end
end

app/views/photos/_form.html.erb
<%# Форма для добавления новой фотографии с одним полем photo %>
<%# Обратите внимание на параметр multipart %>
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: photo} %>

  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit 'Загрузить', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="event-photos buffer-both">
  <div class="event-photo-block">
    <% if current_user_can_edit?(photo) %>
      <% trash_button = link_to(fa_icon('trash'), event_photo_path(photo.event, photo), method: :delete, data: { confirm: t('.confirm') }) %>
    <% end %>
    <% image_title = "#{t('.add')} #{render partial: 'users/user', object: photo.user} #{trash_button}" %>

    <%= link_to image_tag(photo.photo.thumb.url, class: 'event-photo'), photo.photo.url, data: {
        toggle: 'lightbox', title: image_title, gallery: 'event-photos'
    } %>
  </div>
</div>